char *mappers[] = {
    "NROM",
    "UnROM switch",
    "CNROM switch",
    "MMC3",
    "MMC5",
    "FFE F4xxx",
    "AOROM switch",
    "FFE F3xxx",
    "MMC2",
    "MMC4",
    "ColorDreams chip",
    "FFE F6xxx",
    "CPROM switch",
    '\0',
    "100-in-1 switch",
    "Bandai chip",
    "FFE F8xxx",
    "Jaleco SS8806",
    "Namcot 106",
    "Nintendo DiskSystem",
    "Konami VRC4a",
    "Konami VRC2a",
    "Konami VRC4a?",
    "Konami VRC6",
    "Konami VRC4b",
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    "Irem G-101 chip",
    "Taito TC0190/TC0350",
    "Nina-1",
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    "Tengen RAMBO-1 chip",
    "Irem H-3001 chip",
    "GNROM switch",
    "SunSoft3 chip",
    "SunSoft4 chip",
    "SunSoft5 FME-7 chip",
    '\0',
    "Camerica chip",
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    "Irem 74HC161/32-based",
    "AVE Nina-3 board",
    '\0',
    "AVE Nina-6 board",
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    "Pirate HK-SF3 chip"
     };
